import cv2
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = cv2.absdiff(array, np.zeros_like(array))
print("Absolute Values:\n", abs_array)
percentiles_flattened = np.percentile(array, [25, 50, 75])
print("\nPercentiles (Flattened Array):", percentiles_flattened)
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print("\nPercentiles (Columns):\n", percentiles_columns)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("\nPercentiles (Rows):\n", percentiles_rows)
mean_val = np.mean(array)
median_val = np.median(array)
std_dev_val = np.std(array)
print(f"\nFlattened Array - Mean: {mean_val}, Median: {median_val}, Standard Deviation: {std_dev_val}")
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_dev_columns = np.std(array, axis=0)
print("\nColumn-wise Mean:", mean_columns)
print("Column-wise Median:", median_columns)
print("Column-wise Standard Deviation:", std_dev_columns)
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_dev_rows = np.std(array, axis=1)
print("\nRow-wise Mean:", mean_rows)
print("Row-wise Median:", median_rows)
print("Row-wise Standard Deviation:", std_dev_rows)
